apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: zipline
            - name: POSTGRES_PASSWORD
              value: QCyK5hQIFyuyCQy0whBk479oc9XL1Wei
            - name: POSTGRES_USER
              value: zipline
          envFrom:
            - configMapRef:
                name: env
          image: postgres:16
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - zipline
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-claim0
      restartPolicy: Always
      volumes:
        - name: postgresql-claim0
          persistentVolumeClaim:
            claimName: postgresql-claim0
