apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zipline
  name: zipline
spec:
  ports:
    - name: "3111"
      port: 3111
      targetPort: 3000
  selector:
    io.kompose.service: zipline
