apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zipline
  name: zipline
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipline
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: zipline
    spec:
      containers:
          name: zipline
        - env:
            - name: DATABASE_URL
              value: postgres://zipline:QCyK5hQIFyuyCQy0whBk479oc9XL1Wei@postgresql:5432/zipline
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/diced/zipline:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /zipline/uploads
              name: zipline-claim0
            - mountPath: /zipline/public
              name: zipline-claim1
            - mountPath: /zipline/themes
              name: zipline-claim2
          name: postgresql
        - env:
            - name: POSTGRES_DB
              value: zipline
            - name: POSTGRES_PASSWORD
              value: QCyK5hQIFyuyCQy0whBk479oc9XL1Wei
            - name: POSTGRES_USER
              value: zipline
          envFrom:
            - configMapRef:
                name: env
          image: postgres:16
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - zipline
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-claim0

            
      restartPolicy: Always
      volumes:
        - name: postgresql-claim0
          persistentVolumeClaim:
            claimName: postgresql-claim0
        - name: zipline-claim0
          persistentVolumeClaim:
            claimName: zipline-claim0
        - name: zipline-claim1
          persistentVolumeClaim:
            claimName: zipline-claim1
        - name: zipline-claim2
          persistentVolumeClaim:
            claimName: zipline-claim2
