apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: zipline
  name: zipline
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipline
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: zipline
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://zipline:QCyK5hQIFyuyCQy0whBk479oc9XL1Wei@postgresql:5432/zipline
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/diced/zipline:latest
          name: zipline
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /zipline/uploads
              name: zipline-claim0
            - mountPath: /zipline/public
              name: zipline-claim1
            - mountPath: /zipline/themes
              name: zipline-claim2
      restartPolicy: Always
      volumes:
        - name: zipline-claim0
          persistentVolumeClaim:
            claimName: zipline-claim0
        - name: zipline-claim1
          persistentVolumeClaim:
            claimName: zipline-claim1
        - name: zipline-claim2
          persistentVolumeClaim:
            claimName: zipline-claim2
